require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ScoreSheetsController do

  # This should return the minimal set of attributes required to create a valid
  # ScoreSheet. As you add validations to ScoreSheet, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "event_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ScoreSheetsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all score_sheets as @score_sheets" do
      score_sheet = ScoreSheet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:score_sheets).should eq([score_sheet])
    end
  end

  describe "GET show" do
    it "assigns the requested score_sheet as @score_sheet" do
      score_sheet = ScoreSheet.create! valid_attributes
      get :show, {:id => score_sheet.to_param}, valid_session
      assigns(:score_sheet).should eq(score_sheet)
    end
  end

  describe "GET new" do
    it "assigns a new score_sheet as @score_sheet" do
      get :new, {}, valid_session
      assigns(:score_sheet).should be_a_new(ScoreSheet)
    end
  end

  describe "GET edit" do
    it "assigns the requested score_sheet as @score_sheet" do
      score_sheet = ScoreSheet.create! valid_attributes
      get :edit, {:id => score_sheet.to_param}, valid_session
      assigns(:score_sheet).should eq(score_sheet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ScoreSheet" do
        expect {
          post :create, {:score_sheet => valid_attributes}, valid_session
        }.to change(ScoreSheet, :count).by(1)
      end

      it "assigns a newly created score_sheet as @score_sheet" do
        post :create, {:score_sheet => valid_attributes}, valid_session
        assigns(:score_sheet).should be_a(ScoreSheet)
        assigns(:score_sheet).should be_persisted
      end

      it "redirects to the created score_sheet" do
        post :create, {:score_sheet => valid_attributes}, valid_session
        response.should redirect_to(ScoreSheet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved score_sheet as @score_sheet" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreSheet.any_instance.stub(:save).and_return(false)
        post :create, {:score_sheet => { "event_id" => "invalid value" }}, valid_session
        assigns(:score_sheet).should be_a_new(ScoreSheet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreSheet.any_instance.stub(:save).and_return(false)
        post :create, {:score_sheet => { "event_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested score_sheet" do
        score_sheet = ScoreSheet.create! valid_attributes
        # Assuming there are no other score_sheets in the database, this
        # specifies that the ScoreSheet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ScoreSheet.any_instance.should_receive(:update_attributes).with({ "event_id" => "1" })
        put :update, {:id => score_sheet.to_param, :score_sheet => { "event_id" => "1" }}, valid_session
      end

      it "assigns the requested score_sheet as @score_sheet" do
        score_sheet = ScoreSheet.create! valid_attributes
        put :update, {:id => score_sheet.to_param, :score_sheet => valid_attributes}, valid_session
        assigns(:score_sheet).should eq(score_sheet)
      end

      it "redirects to the score_sheet" do
        score_sheet = ScoreSheet.create! valid_attributes
        put :update, {:id => score_sheet.to_param, :score_sheet => valid_attributes}, valid_session
        response.should redirect_to(score_sheet)
      end
    end

    describe "with invalid params" do
      it "assigns the score_sheet as @score_sheet" do
        score_sheet = ScoreSheet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreSheet.any_instance.stub(:save).and_return(false)
        put :update, {:id => score_sheet.to_param, :score_sheet => { "event_id" => "invalid value" }}, valid_session
        assigns(:score_sheet).should eq(score_sheet)
      end

      it "re-renders the 'edit' template" do
        score_sheet = ScoreSheet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ScoreSheet.any_instance.stub(:save).and_return(false)
        put :update, {:id => score_sheet.to_param, :score_sheet => { "event_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested score_sheet" do
      score_sheet = ScoreSheet.create! valid_attributes
      expect {
        delete :destroy, {:id => score_sheet.to_param}, valid_session
      }.to change(ScoreSheet, :count).by(-1)
    end

    it "redirects to the score_sheets list" do
      score_sheet = ScoreSheet.create! valid_attributes
      delete :destroy, {:id => score_sheet.to_param}, valid_session
      response.should redirect_to(score_sheets_url)
    end
  end

end
